### ISSUE TITLE
file not found error (running in terminal)

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/canvas-get-group-csv#8]
Attempted to run in terminal - error generating output

`Traceback (most recent call last):
  File "/Users/al2myers/Documents/GitHub/Sauder-Learning-Services/canvas-get-group-csv/src/get_group_csv.py", line 71, in <module>
    main()
  File "/Users/al2myers/Documents/GitHub/Sauder-Learning-Services/canvas-get-group-csv/src/get_group_csv.py", line 67, in main
    _create_csv(df, output_name)
  File "/Users/al2myers/Documents/GitHub/Sauder-Learning-Services/canvas-get-group-csv/src/helpers.py", line 19, in _create_csv
    df.to_csv(output_name, index=False)
  File "/anaconda3/envs/canvas-universal-env/lib/python3.9/site-packages/pandas/core/generic.py", line 3384, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/anaconda3/envs/canvas-universal-env/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/anaconda3/envs/canvas-universal-env/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 228, in save
    with get_handle(
  File "/anaconda3/envs/canvas-universal-env/lib/python3.9/site-packages/pandas/io/common.py", line 639, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'output/4031_Teaching Online Playbook - V1.19 - 01/12/2021_Group Information_2021-01-15_131755.csv'`

**Comment by alisonmyers** [comment]
error in jupyter as well
- guessing has to do with folder structure

**Comment by alisonmyers** [comment]
Error - due to course name - need to make sure that course names don't have symbols that interfere with file paths

**Comment by markoprodanovic** [comment]
> Error - due to course name - need to make sure that course names don't have symbols that interfere with file paths

Could you share with me the course name that caused the bug?

**Comment by alisonmyers** [comment]
output/4031_Teaching Online Playbook - V1.19 - 01/12/2021_Group Information_2021-01-15_131755.csv

**Comment by markoprodanovic** [comment]
Would it be reasonable to make small adjustments to the name?

I'm thinking, write a function that'll look for any '/' character and replace it with '-'

`output/4031_Teaching Online Playbook - V1.19 - 01/12/2021_Group Information_2021-01-15_131755.csv`

becomes

`output/4031_Teaching Online Playbook - V1.19 - 01-12-2021_Group Information_2021-01-15_131755.csv`

**Comment by alisonmyers** [comment]
yep, makes sens to me. maybe any character that isn't a space, underscore, or dash should become a dash?

**Comment by markoprodanovic** [comment]
Closed by #9
